### ISSUE TITLE
[suggestion] upload asset on github

### ISSUE THREAD

**Issue by numToStr** [haringsrob/nvim_context_vt#11]
Thanks for this nice plugin.

I noticed that you have a >3Mb demo gif file that is used in the readme. It would be a better experience and make your plugin lighter if you can upload that on GitHub as GitHub already supports file uploads for readme.

**Comment by haringsrob** [comment]
![jif](https://user-images.githubusercontent.com/866743/128077347-051430c4-2c89-4161-aa48-5a5793ec8499.gif)

I will upload it here :) thanks for the suggestion.
