### ISSUE TITLE
 Show catch and show function name

### ISSUE THREAD

**Issue by adelin-b** [haringsrob/nvim_context_vt#16]
Hello, I found two case that are not handled correctly
- Catch block are ignored
![image](https://user-images.githubusercontent.com/23508913/138052424-2bad732d-467b-44ba-982b-c0a7310991df.png)
- Some argument block don't show the parenthesis function name
![image](https://user-images.githubusercontent.com/23508913/138052540-2e4e1f8f-5539-47e3-a662-f939f45abbce.png)

**Comment by andersevenrud** [comment]
I opened a PR for this :)

https://github.com/haringsrob/nvim_context_vt/pull/20

**Comment by andersevenrud** [comment]
> Some argument block don't show the parenthesis function name

Note that i did not cover the this because it's not a regular statement or function expression. I'll see about this in another PR because it's probably language specific.

Edit: Indeed it is. In ts/js for example this is not available via a distinct node type.
