### ISSUE TITLE
Virtual text color

### ISSUE THREAD

**Issue by zibertszn** [haringsrob/nvim_context_vt#56]
How can i switch virtual text color?

**Comment by andersevenrud** [comment]
Hi,

You can override the default highlighting group with ex: `hi ContextVt guifg=#ff0000`.

**Comment by andersevenrud** [comment]
Default value is located here: 
https://github.com/haringsrob/nvim_context_vt/blob/bcc89cabb4841134c9aec66480499ccfac0331d6/plugin/nvim_context_vt.vim#L1
