### ISSUE TITLE
Config option to start disabled

### ISSUE THREAD

**Issue by ristillu** [haringsrob/nvim_context_vt#57]
This seems like a really useful plugin. Would it be possible to have an option to start disabled? I installed it and am playing with it but my editor environment can get quite noisy and I like to toggle things on and off when I want them. E.g. I use blamer.nvim very occasionally. It's indispensible when I want it turned on, but I don't want it turned on very often. It seems I would want nvim_context_vt turned on more often, but still not all the time (and not by default at startup).

**Comment by andersevenrud** [comment]
Thanks for the suggestion! I'll implement this ASAP.

**Comment by andersevenrud** [comment]
You should now be able to do:

```
require('nvim_context_vt').setup({
  enabled = false,
})
```

And then `:NvimContextVtToggle` to manually enable on demand.

**Comment by ristillu** [comment]
Thanks for the quick implementation!
