### ISSUE TITLE
Golang nested struct doesn't work

### ISSUE THREAD

**Issue by mortymacs** [haringsrob/nvim_context_vt#67]
Hi,

In Golang, when we have nested struct it doesn't work completely:
![image](https://github.com/haringsrob/nvim_context_vt/assets/1261448/8e3f2489-d888-47fc-89ec-fdb381984621)

While it works fine in nested dictionary:
![image](https://github.com/haringsrob/nvim_context_vt/assets/1261448/94105b7d-2606-49d9-9492-4464d23b7c32)

My config:
```lua
require("nvim_context_vt").setup({
  disable_virtual_lines = true,
  disable_ft = { "markdown", "yaml" },
})
```

Thank you!

**Comment by andersevenrud** [comment]
Could you do `:NvimContextVtDebug` when your cursor is in the position in the screenshot above ?

That should contain the information I need to fix this.

**Comment by mortymacs** [comment]
Sure, it's the result:
![image](https://github.com/haringsrob/nvim_context_vt/assets/1261448/5ab8ea84-2113-47ae-b11d-076c342a1c8d)

**Comment by mortymacs** [comment]
I could fix it locally by updating the config list with these new items:

```lua
    'field_declaration',
    'struct_type',
```

Can I send a PR?

**Comment by andersevenrud** [comment]
PR is much appreciated 👌
