### ISSUE TITLE
[FR] print Lua variable names when function is assigned to a variable

### ISSUE THREAD

**Issue by andrewcrook** [haringsrob/nvim_context_vt#73]
I was just testing this plugin to see if I will add it to my new configuration.

If I do the following in Lua an anonymous function assigned to a variable.

```Lua
{ 'andersevenrud/nvim_context_vt'
     config = function()
         -- do something
     end → function
},
```

The plugin works by showing the closing function.
However, it would be useful to show the variable name that the function is assigned to.
Something like ... 

```Lua
end → config => function
```
of course, this is probably the same for other language support.

**Comment by andersevenrud** [comment]
> However, it would be useful to show the varible name that the function is assigned to.

I'll look into it. Not sure about adding something like this as builtin because the nodes varies between languages etc., but adding some examples on how to do this via custom callbacks in the configuration would be useful!

**Comment by andrewcrook** [comment]
being able to do this via custom callback (i.e completely optional) for individual languages would be great.

**Comment by andersevenrud** [comment]
Turns out there was a much simpler solution to this. Just update and it should be working :)
